package org.example.loginspring_adriansaavedra.common;

public class Constantes {
    public static final String LOGIN_DIR = "/login";
    public static final String PLAYERS_DIR = "/players";
    public static final String REGISTER_DIR = "/register";
    public static final String FAVORITES_DIR = "/favorites";
    public static final String VERIFY_DIR = "/verify";
    public static final String REFRESH_DIR = "/refresh";
    public static final String SUCCESS_MESSAGE = "Your account has been verified. You can now log in.";
    public static final String EXPIRED_CODE_MESSAGE = "Invalid or expired verification code.";
    public static final String SPRING_MAIL_USERNAME = "spring.mail.username";
    public static final String EMAIL_VERIFICATION_SUBJECT = "Email Verification";
    public static final String LINK_VERIFY = "http://localhost:8080/verify?code=";
    public static final String PLEASE_CLICK_ON_THE_LINK_TO_VERIFY_YOUR_EMAIL = "Please click on the link to verify your email: ";
    public static final String ID_ARGUMENT = "/{id}";
    public static final String BEARER = "Bearer ";
    public static final String SERVIDOR = "Servidor";
    public static final String SHA_512 = "SHA-512";
    public static final String AES = "AES";
    public static final String CLAVE = "clave";
    public static final String INIT_EXP = "${";
    public static final String END_EXP = "}";
    public static final String USERNAME_PARAM = "username";
    public static final String EMAIL_PARAM = "email";
    public static final String CODE_PARAM = "code";
    public static final String ROLENAME_PARAM = "roleName";
    public static final String NAME_PARAM = "name";
    public static final String PLAYER_PARAM = "player";
    public static final String CURRENT_ID_PARAM = "currentId";
    public static final String ACCESS_TOKEN = "access_token";
    public static final String REFRESH_TOKEN = "refresh_token";
    public static final String USER_S = "user";
    public static final String COMPULSORY_FILLED = "All fields must be filled";
    public static final String PLAYER_NOT_FOUND = "Player not found";
    public static final String USER_NOT_FOUND = "User not found ";
    public static final String USER_ALREADY_EXISTS = "User already exists";
    public static final String USER_NOT_VERIFIED = "User not verified";
    public static final String PLAYER_FAVORITE_ALREADY_EXISTS = "Player favorite already exists";
    public static final String PLAYER_ALREADY_EXISTS = "Player already exists: ";
    public static final String SUCCESS_REGISTER = "Your account has been registered. Go to the mail.";
    public static final String ROLE_NOT_FOUND = "Role not found: ";
    public static final String SQL_VERIFY_USER_EXISTS = "SELECT COUNT(c) FROM CredentialEntity c WHERE c.username = :username OR c.email = :email";
    public static final String SQL_FIND_BY_VERIFICATION_CODE = "SELECT c FROM CredentialEntity c WHERE c.verificationCode = :code";
    public static final String SQL_FIND_ROLE_BY_NAME = "SELECT r FROM RoleEntity r WHERE r.rol = :roleName";
    public static final String SQL_FIND_BY_USERNAME = "SELECT c FROM CredentialEntity c WHERE c.username = :username";
    public static final String SQL_GET_ALL_PLAYERS = "SELECT p FROM PlayerEntity p";
    public static final String SQL_PLAYER_EXISTS_EXCLUDING_CURRENT = "SELECT COUNT(p) FROM PlayerEntity p WHERE LOWER(p.name) = LOWER(:name) AND p.id != :currentId";
    public static final String SQL_PLAYER_EXISTS = "SELECT COUNT(p) FROM PlayerEntity p WHERE LOWER(p.name) = LOWER(:name)";
    public static final String SQL_ADD_PLAYER_FOR_USER = "SELECT p FROM PlayerEntity p WHERE LOWER(p.name) = LOWER(:name)";
    public static final String SQL_GET_CREDENTIAL_BY_USERNAME = "SELECT c FROM CredentialEntity c WHERE c.username = :username";
    public static final String SQL_DELETE_PLAYER = "SELECT c FROM CredentialEntity c WHERE :player MEMBER OF c.favoritePlayerEntities";
    public static final String CREDENTIALS = "credentials";
    public static final String PLAYERS = "players";
    public static final String ROLES = "roles";
    public static final String ROLE_ID = "role_id";
    public static final String USER_FAVORITE_PLAYERS = "user_favorite_players";
    public static final String USER_ID = "user_id";
    public static final String PLAYER_ID = "player_id";
    public static final String ROLE_BAR = "ROLE_";
    public static final String USER_UPPER = "USER";
    public static final String AT_LEAST_NAME_AND_COUNTRY_MUST_BE_FILLED = "At least name and country must be filled";
    public static final String HAS_ROLE_ADMIN = "hasRole('ADMIN')";
    public static final String HAS_ROLE_USER = "hasRole('USER')";
    public static final String HAS_ROLE_ADMIN_OR_USER = "hasRole('ADMIN') or hasRole('USER')";
    public static final String THIS_ACCOUNT_HAS_NOT_BEEN_VERIFIED = "This account exists but has not been verified. Please check the mail where you registered.";
    public static final String CHECK_IF_EMAIL_OR_USERNAME_IS_ALREADY_REGISTERED = ". Check if email or username is already registered";
    public static final String THE_ACCOUNT_DOES_NOT_EXIST = "The account does not exist. Please register.";
    public static final String PLAYER_NOT_IN_FAVORITES =  "Player not in favorites";
}
