POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "a",
  "password": "a"
}


###
@login = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhIiwiaXNzIjoiU2Vydmlkb3IiLCJpYXQiOjE3Mzk1NzYxMTcsImV4cCI6MTczOTU3NzAxNywidXNlciI6ImEifQ.tpIqV9Ww5nSs_AfmTAt4oJS2_XLaUNyik5_TsBtLAuKaYlYc1m6Yry3o6LhpQSNGQwAGrepbIL4sWXCnhCBRvw
@refresh = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhIiwiaXNzIjoiU2Vydmlkb3IiLCJpYXQiOjE3Mzk1NzYwNDEsImV4cCI6MTc0MDE4MDg0MSwidXNlciI6ImEifQ.mZHdVEQKs1SGvvna6U8ZPTX9CssTP1zy3j3kj-ZmItrC2GSffsT3TsucilTOlXxopcefjuaGpVcUZrBi8U0LNA


### Register
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "a",
  "password": "a",
  "email": "saavedra.mateo.walter@gmail.com"
}





### Refresh Token
POST http://localhost:8080/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{refresh}}"
}


### Use Access Token
GET http://localhost:8080/players
Authorization: Bearer {{login}}

### Get Player by ID
GET http://localhost:8080/players/1
Authorization: Bearer your_access_token_here

### Add Player
POST http://localhost:8080/players
Content-Type: application/json
Authorization: Bearer your_access_token_here

{
  "name": "New Player",
  "position": "Forward",
  "team": "Team A"
}

### Update Player
PUT http://localhost:8080/players/1
Content-Type: application/json
Authorization: Bearer your_access_token_here

{
  "name": "Updated Player",
  "position": "Midfielder",
  "team": "Team B"
}

### Delete Player
DELETE http://localhost:8080/players/1
Authorization: Bearer your_access_token_here

### Get Favorite Players
GET http://localhost:8080/favorites/1
Authorization: Bearer your_access_token_here

### Get Favorite Player
GET http://localhost:8080/favorites/1/1
Authorization: Bearer your_access_token_here

### Add Favorite Player
POST http://localhost:8080/favorites/1/1
Authorization: Bearer your_access_token_here

### Delete Favorite Player
DELETE http://localhost:8080/favorites/1/1
Authorization: Bearer your_access_token_here